name: Server Dagger CI

on:
  workflow_call:
  push:
    branches:
      - develop

jobs:
  dagger-server-ci:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v3
      - 
        name: Dagger CI Server
        uses: dagger/dagger-for-github@v3.0.0
        with:
          workdir: ./
          cmds: |
            project init
            project update
            do test